# flake8: noqa

"""
    Arbeitsagentur Weiterbildungssuche API

    Eine der größten Weiterbildungsdatenbanken Deutschlands durchsuchen.  Die Authentifizierung funktioniert über die clientId der Weiterbildungssuche, die einem GET-request an https://web.arbeitsagentur.de/weiterbildungssuche/suche entnommen werden kann:  clientId: infosysbub-wbsuche  Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.     # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.1.0"

# import ApiClient
from deutschland.weiterbildungssuche.api_client import ApiClient

# import Configuration
from deutschland.weiterbildungssuche.configuration import Configuration

# import exceptions
from deutschland.weiterbildungssuche.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
