"""
    Arbeitsagentur Weiterbildungssuche API

    Eine der größten Weiterbildungsdatenbanken Deutschlands durchsuchen.  Die Authentifizierung funktioniert über die clientId der Weiterbildungssuche, die einem GET-request an https://web.arbeitsagentur.de/weiterbildungssuche/suche entnommen werden kann:  clientId: infosysbub-wbsuche  Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.     # noqa: E501

    The version of the OpenAPI document: 2.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.weiterbildungssuche.api.default_api import DefaultApi  # noqa: E501

from deutschland import weiterbildungssuche


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_facetten(self):
        """Test case for facetten

        Facetten  # noqa: E501
        """
        pass

    def test_weiterbildungssuche(self):
        """Test case for weiterbildungssuche

        Weiterbildungssuche  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
